import { Montserrat } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import Sidebar from "@/components/admin/App-Sidebar";
import { Separator } from "@/components/ui/separator";
import PanelBreadCrumb from "@/components/admin/PanelBreadCrumb";

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
    display: "swap",
})
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${montserrat.variable} antialiased h-screen min-h-screen overflow-auto`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <SidebarProvider>
                        <Sidebar />
                        <main className="flex-1 overflow-auto">
                            <div className="bg-sidebar h-12 flex items-center p-2 fixed top-0 w-full">
                                <SidebarTrigger />
                                <Separator
                                    orientation="vertical"
                                    className="mx-2 data-[orientation=vertical]:h-4"
                                />
                                <PanelBreadCrumb />
                            </div>
                            {children}
                        </main>
                    </SidebarProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
