import { Montserrat } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { SidebarProvider } from '@/components/ui/sidebar'
import Sidebar from "@/components/admin/App-Sidebar";
import PanelHeader from "@/components/admin/PanelHeader";

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
    display: "swap",
})
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${montserrat.variable} antialiased h-screen min-h-screen overflow-auto`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <SidebarProvider>
                        <div className="grid grid-cols-[auto_1fr] w-full grid-rows-[auto_1fr] h-screen">
                            <Sidebar className="row-span-2" />

                            <PanelHeader />

                            <main className="overflow-auto col-start-2">
                                {children}
                            </main>
                        </div>
                    </SidebarProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
